<?php

// This file is automatically generated by Laravel...

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\VoltServiceProvider::class,
    DraftScripts\Permission\PermissionServiceProvider::class,
    DraftScripts\BdLocation\BdLocationServiceProvider::class,
];
